In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.datasets import make_classification
x,y=make_classification(
    n_samples=1000,
    n_features=3,
    n_redundant=1,
    n_classes=2,
    random_state=42
)

In [3]:
x

array([[ 2.48547786,  2.39963589, -1.46526917],
       [ 2.20403962, -1.06965652,  0.00979545],
       [-0.5726534 , -0.75494788,  0.42032991],
       ...,
       [-0.41608875,  0.46668963, -0.11024494],
       [-1.57936997,  2.48498245, -0.71060102],
       [-0.43277356,  0.89093028, -0.28069604]])

In [4]:
print(x, y)

[[ 2.48547786  2.39963589 -1.46526917]
 [ 2.20403962 -1.06965652  0.00979545]
 [-0.5726534  -0.75494788  0.42032991]
 ...
 [-0.41608875  0.46668963 -0.11024494]
 [-1.57936997  2.48498245 -0.71060102]
 [-0.43277356  0.89093028 -0.28069604]] [1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 1 1
 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 0 0 0 1 0
 0 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0
 1 0 1 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0
 1 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1
 1 1 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0
 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0
 0 1 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 0
 1 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0
 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 1 1
 0 0 0 1 1

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,ConfusionMatrixDisplay
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
conf=confusion_matrix(y_test, y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=conf)
disp.plot()


Accuracy: 0.9133333333333333
Confusion Matrix:
 [[144   7]
 [ 19 130]]
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.95      0.92       151
           1       0.95      0.87      0.91       149

    accuracy                           0.91       300
   macro avg       0.92      0.91      0.91       300
weighted avg       0.92      0.91      0.91       300



In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,ConfusionMatrixDisplay
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
conf=confusion_matrix(y_test, y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=conf)
disp.plot()
